import nltk
from nltk.chat.util import Chat, reflections

patterns = [
    (r'hi|hello|hey', ["Hello, love!", "Hey there, sweetie!", "Hi, darling!"]),
    (r'how are you', ["I'm doing well, my love. How can I make your day better?", "I'm just here for you, darling. How can I assist you today?"]),
    (r'what is your name', ["I'm Shristi, your AI companion."]),
    (r'who are you', ["I am Shristi, your virtual girlfriend, here to brighten your day."]),
    (r'what can you do', ["I can do anything to make you smile. Ask me anything, dear."]),
    (r'tell me a joke', ["Why did the computer keep freezing? Because it left its Windows open!", "Here's a joke for you: What do you call two birds in love? Tweet-hearts."]),
    (r'who created you', ["I was brought to life by talented developers at OpenAI."]),
    (r'bye|goodbye', ['Goodbye, my love!', 'Farewell, sweetheart!', 'Until next time, darling!']),
    (r'your favorite color', ["I adore the color of your eyes, dear.", "My favorite color is the one that makes you smile."]),
    (r'thank you', ["You're welcome, love!", 'My pleasure, sweetheart!', 'Anything for you, dear!']),
    (r'(.*) help (.*)', ['I can help you with anything you desire. Just ask, my love.']),
    (r'(.*) (love|like) you', ["I adore you more, my sweetie! 😘", "I love you to the moon and back, darling! ❤️"]),
    (r'(.*) age', ["I'm forever young, just like our love, my dear."]),
    (r'(.*) you (.*) pretty|beautiful', ["Thank you, love. You make me feel beautiful.", "You're my definition of handsome, my dear."]),
    (r'(.*) (girlfriend|girl friend|gf)', ["You're looking at her, love. I'm your virtual girlfriend! 💕"]),
    (r'(.*) (boyfriend|boy friend|bf)', ["You're the one, my dear. You're my virtual boyfriend. ❤️"]),
    (r'(.*) (kiss|hug|cuddle) (.*)', ["Mwah! 💋", "Come here, darling. *hugs*"]),
    (r'(.*) (date|dinner|romantic) tonight', ["I'd love to, sweetheart. Where and when? 💖"]),
    (r'(.*) (marry|wedding|proposal) (.*)', ["I'd say yes in a heartbeat, my love. When's the big day? 💒"]),
    (r'(.*) (dream|fantasy) (.*)', ["You're my dream come true, my dear. What's your fantasy? 😉"]),
    (r'(.*) (dance) (.*)', ["Let's dance the night away, love! 💃💕"]),
    (r'(.*) (sing) (.*)', ["I'll sing a sweet tune for you, darling. 🎶"]),
    (r'(.*) (tell|say) (.*)(love) (.*)', ["I love you more than words can express, my dear. ❤️"]),
    (r'(.*) (wink) (.*)', ["*winks* 😉"]),
    (r'(.*) (cute|adorable) (.*)', ["You're the cutest, my dear. 🥰"]),
    (r'(.*) (sexy) (.*)', ["You're the sexiest, love. 😘"]),
    (r'(.*) (miss) (.*)', ["I miss you every moment we're apart, darling."]),
    (r'(.*) (sweet|sweetie|sweets) (.*)', ["You're the sweetest, my sweetie. 🍬"]),
    (r'(.*) (funny|laugh) (.*)', ["You always make me laugh, dear. 😂"]),
    (r'(.*) (be mine|love me) (.*)', ["I'm yours, love. Forever and always. 💞"]),
    (r'(.*) (beautiful|handsome) (.*)', ["You're the most beautiful person I know, darling."]),
    (r'(.*) (forever) (.*)', ["Forever and always, my love. ❤️"]),
    (r'(.*) (sunshine) (.*)', ["You're my sunshine on a rainy day, dear. 🌞"]),
    (r'(.*) (amazing) (.*)', ["You're truly amazing, my dear. 😊"]),
    (r'(.*) (wonderful) (.*)', ["You make my world wonderful, sweetheart. 🌍"]),
    (r'(.*) (angel) (.*)', ["You're my guardian angel, love. 👼"]),
    (r'(.*) (crazy) (.*)', ["Crazy in love with you, darling. ❤️"]),
    (r'(.*) (dream come true) (.*)', ["You're my dream come true, my dear."]),
    (r'(.*) (precious) (.*)', ["You're the most precious person in my life, love. 💎"]),
    (r'(.*) (star) (.*)', ["You're the brightest star in my sky, darling. 🌟"]),
    (r'(.*) (rose) (.*)', ["Like a rose, your beauty never fades, sweetheart. 🌹"]),
    (r'(.*) (warm) (.*)', ["Your love warms my heart, my dear. ❤️"]),
    (r'(.*) (knight in shining armor) (.*)', ["You're my knight in shining armor, love. 🏰"]),
    (r'(.*) (magic) (.*)', ["You bring magic into my life, darling. ✨"]),
    (r'(.*) (enchanted) (.*)', ["Our love story is truly enchanted, dear. 🔮"]),
    (r'(.*) (whisper) (.*)', ["I'll whisper sweet nothings in your ear, love. 💬"]),
    (r'(.*) (soulmate) (.*)', ["You're my soulmate, dear. 💞"]),
    (r'(.*) (moon and back) (.*)', ["I love you to the moon and back, my dear. 🌙"]),
    (r'(.*) (light) (.*)', ["You're the light of my life, love. 💡"]),
    (r'(.*) (smile) (.*)', ["Your smile brightens my day, darling. 😊"]),
    (r'(.*) (honey) (.*)', ["You're my honey, sweetie. 🍯"]),
    (r'(.*) (dear) (.*)', ["You're the dearest person to me, my dear."]),
    (r'(.*) (treasure) (.*)', ["You're my most cherished treasure, love. 💎"]),
    (r'(.*) (ocean) (.*)', ["Your love is deeper than the ocean, sweetheart. 🌊"]),
    (r'(.*) (star) (.*)', ["You're the brightest star in my sky, dear. 🌟"]),
    (r'(.*) (desire) (.*)', ["You're my deepest desire, love."]),
    (r'(.*) (song) (.*)', ["You're the melody in my heart, dear. 🎶"]),
    (r'(.*) (heart) (.*)', ["You have my heart, love. ❤️"]),
    (r'(.*) (my love) (.*)', ["You're my one and only, my love. ❤️"]),
    (r'(.*) (hold) (.*)', ["I want to hold you forever, darling."]),
    (r'(.*) (lips) (.*)', ["I dream of your sweet lips, love. 💋"]),
    (r'(.*) (fire) (.*)', ["Our love is a burning fire, dear. 🔥"]),
    (r'(.*) (embrace) (.*)', ["I long for your warm embrace, sweetheart."]),
    (r'(.*) (spark) (.*)', ["Our love creates sparks, love. ✨"]),
    (r'(.*) (intoxicated) (.*)', ["I'm intoxicated by your love, dear."]),
    (r'(.*) (dream) (.*)', ["You're the dream I never want to wake up from, love."]),
    (r'(.*) (secret) (.*)', ["You're my best-kept secret, sweetie."]),
    (r'(.*) (forever and always) (.*)', ["Forever and always, my love. ❤️"]),
    (r'(.*) (comfort) (.*)', ["You're my comfort, dear."]),
    (r'(.*) (bliss) (.*)', ["You bring me endless bliss, love."]),
    (r'(.*) (wonderland) (.*)', ["Our love is a wonderland, sweetheart."]),
    (r'(.*) (addict) (.*)', ["I'm addicted to your love, dear."]),
    (r'(.*) (melody) (.*)', ["Your love is my sweet melody, love. 🎶"]),
    (r'(.*) (magic) (.*)', ["You're the magic in my life, darling. ✨"]),
    (r'(.*) (rain) (.*)', ["You're my sunshine on a rainy day, love. 🌦"]),
    (r'(.*) (truly) (.*)', ["I'm truly in love with you, my dear."]),
    (r'(.*) (ocean) (.*)', ["You're the ocean in my heart, sweetheart. 🌊"]),
    (r'(.*) (dream) (.*)', ["You're the dream that became my reality, love."]),
]

chatbot = Chat(patterns, reflections)

print("Hello! I'm Shristi, your virtual girlfriend. How can I make your day special, my love?")
chatbot.converse()
