import random
from enum import Enum

class Gender(Enum):
	MALE = 'male'
	FEMALE = 'female'

compliments = [
    "You're truly exceptional!",
    "You make the world a better place.",
    "Your kindness knows no bounds.",
    "You're a beacon of hope for others.",
    "You have a heart of gold.",
    "You radiate positivity and joy.",
    "You're an absolute delight to be around.",
    "Your energy is infectious.",
    "You're an inspiration to us all.",
    "You're incredibly talented and capable.",
    "You have an amazing sense of humor.",
    "You light up every room you enter.",
    "You're a constant source of motivation.",
    "Your presence is a gift to those around you.",
    "You're always there to lend a helping hand.",
    "You're a true role model.",
    "You're a superstar in every way.",
    "You have an unshakable spirit.",
    "You're a true force of nature.",
    "You have an extraordinary sense of style.",
    "You're a master of your craft.",
    "You have a heart full of compassion.",
    "You're a remarkable friend and confidant.",
    "You're the epitome of grace and elegance.",
    "You're incredibly intelligent and insightful.",
    "You're a constant source of inspiration.",
    "Your positivity is absolutely infectious.",
    "You're a true gem of a person.",
    "You're a marvel of creativity.",
    "You make the impossible look easy.",
    "You're an absolute genius.",
    "You're always the life of the party.",
    "You're a true work of art.",
    "You're a gift to the world.",
    "You're truly one in a million.",
    "Your smile brightens even the darkest days.",
    "You're an absolute joy to be around.",
    "You're an unstoppable force of nature.",
    "You have an unbreakable spirit.",
    "You're the definition of a hero.",
    "You're a true visionary.",
    "You're a true example of resilience.",
    "Your wisdom is boundless.",
    "You're a source of endless positivity.",
    "You're a beacon of light in the world.",
    "You're a constant source of strength.",
    "You're a shining star in the universe.",
    "You're an absolute legend.",
    "You're the embodiment of courage.",
    "You're a true inspiration to others.",
    "You're a master of your domain.",
    "You're a rare and precious gem.",
    "You're the best at what you do.",
    "You have a heart full of kindness.",
    "You're the definition of excellence.",
    "You're a paragon of virtue.",
    "You're always there when it matters most.",
    "You're a true pioneer of innovation.",
    "You're a true source of joy and laughter.",
    "You're the model of consistency.",
    "You're an absolute treasure.",
    "You have a heart full of generosity.",
    "You're a true inspiration to us all.",
    "You're a true artist of life.",
    "You're an absolute marvel of humanity.",
    "You're a true testament to perseverance.",
    "You have a heart full of empathy.",
    "You're a champion in every sense.",
    "You're a source of endless happiness.",
    "You're a guiding light for others.",
    "You're a true embodiment of grace.",
    "You're a constant source of kindness.",
    "You're an absolute powerhouse.",
    "You're a true gift to the world.",
    "You have an amazing aura.",
    "You're the embodiment of strength.",
    "You're always the voice of reason.",
    "You're a true symbol of hope.",
    "You're a true pioneer of change.",
    "You're the very definition of beauty.",
    "You're a true example of excellence.",
    "You have a heart full of compassion.",
    "You're the definition of success.",
    "You're a true icon of inspiration.",
    "You're a beacon of positivity.",
    "You're a constant source of wisdom.",
    "You're an absolute treasure of a person.",
    "You're a true genius in every way.",
    "You're a model of determination.",
    "You have an extraordinary mind.",
    "You're a true force of positivity.",
    "You're a true inspiration to us all.",
    "You're a master of your craft.",
    "You're a true leader in every sense.",
    "You're a shining example of generosity.",
    "You're always the voice of kindness.",
    "You're a true source of joy and laughter.",
    "You're the epitome of grace and elegance.",
    "You're a true source of inspiration to others.",
    "You have a heart full of love and compassion.",
    "You're a true symbol of perseverance.",
    "You're a constant source of strength and support.",
    "You're a beacon of positivity and hope.",
    "You're an absolute marvel of humanity.",
    "You're the embodiment of kindness and goodness.",
    "You're always there when it matters most.",
    "You're a true model of resilience and strength.",
    "You have a heart full of warmth and empathy.",
    "You're a true hero in every way.",
    "You're a beacon of light in the world.",
    "You're a true testament to excellence and brilliance.",
    "You're a true source of inspiration to us all.",
    "You're a master of your domain in every way.",
    "You're a true icon of courage and determination.",
    "You're a model of consistency and reliability.",
    "You're truly exceptional!",
    "You make the world a better place.",
    "Your kindness knows no bounds.",
    "You're a beacon of hope for others.",
    "You have a heart of gold.",
    "You radiate positivity and joy.",
    "You're an absolute delight to be around.",
    "Your energy is infectious.",
    "You're an inspiration to us all.",
    "You're incredibly talented and capable.",
    "You have an amazing sense of humor.",
    "You light up every room you enter.",
    "You're a constant source of motivation.",
    "Your presence is a gift to those around you.",
    "You're always there to lend a helping hand.",
    "You're a true role model.",
    "You're a superstar in every way.",
    "You have an unshakable spirit.",
    "You're a true force of nature.",
    "You have an extraordinary sense of style.",
    "You're a master of your craft.",
    "You have a heart full of compassion.",
    "You're a remarkable friend and confidant.",
    "You're the epitome of grace and elegance.",
    "You're incredibly intelligent and insightful.",
    "You're a constant source of inspiration.",
    "Your positivity is absolutely infectious.",
    "You're a true gem of a person.",
    "You're a marvel of creativity.",
    "You make the impossible look easy.",
    "You're an absolute genius.",
    "You're always the life of the party.",
    "You're a true work of art.",
    "You're a gift to the world.",
    "You're truly one in a million.",
    "Your smile brightens even the darkest days.",
    "You're an absolute joy to be around.",
    "You're an unstoppable force of nature.",
    "You have an unbreakable spirit.",
    "You're the definition of a hero.",
    "You're a true visionary.",
    "You're a true example of resilience.",
    "Your wisdom is boundless.",
    "You're a source of endless positivity.",
    "You're a beacon of light in the world.",
    "You're a constant source of strength.",
    "You're a shining star in the universe.",
    "You're an absolute legend.",
    "You're the embodiment of courage.",
    "You're a true inspiration to others.",
    "You're a master of your domain.",
    "You're a rare and precious gem.",
    "You're the best at what you do.",
    "You have a heart full of kindness.",
    "You're the definition of excellence.",
    "You're a paragon of virtue.",
    "You're always there when it matters most.",
    "You're a true pioneer of innovation.",
    "You're a true source of joy and laughter.",
    "You're the model of consistency.",
    "You're an absolute treasure.",
    "You have a heart full of generosity.",
    "You're a true inspiration to us all.",
    "You're a true artist of life.",
    "You're an absolute marvel of humanity.",
    "You're a true testament to perseverance.",
    "You have a heart full of empathy.",
    "You're a champion in every sense.",
    "You're a source of endless happiness.",
    "You're a guiding light for others.",
    "You're a true embodiment of grace.",
    "You're a constant source of kindness.",
    "You're an absolute powerhouse.",
    "You're a true gift to the world.",
    "You have an amazing aura.",
    "You're the embodiment of strength.",
    "You're always the voice of reason.",
    "You're a true symbol of hope.",
    "You're a true pioneer of change.",
    "You're the very definition of beauty.",
    "You're a true example of excellence.",
    "You have a heart full of compassion.",
    "You're the definition of success.",
    "You're a true icon of inspiration.",
    "You're a beacon of positivity.",
    "You're a constant source of wisdom.",
    "You're an absolute treasure of a person.",
    "You're a true genius in every way.",
    "You're a model of determination.",
    "You have an extraordinary mind.",
    "You're a true force of positivity.",
    "You're a true inspiration to us all.",
    "You're a master of your craft.",
    "You're a true leader in every sense.",
    "You're a shining example of generosity.",
    "You're always the voice of kindness.",
    "You're a true source of joy and laughter.",
    "You're the epitome of grace and elegance.",
    "You're a true source of inspiration to others.",
    "You have a heart full of love and compassion.",
    "You're a true symbol of perseverance.",
    "You're a constant source of strength and support.",
    "You're a beacon of positivity and hope.",
    "You're an absolute marvel of humanity.",
    "You're the embodiment of kindness and goodness.",
    "You're always there when it matters most.",
    "You're a true model of resilience and strength.",
    "You have a heart full of warmth and empathy.",
    "You're a true hero in every way.",
    "You're a beacon of light in the world.",
    "You're a true testament to excellence and brilliance.",
    "You're a true source of inspiration to us all.",
    "You're a master of your domain in every way.",
    "You're a true icon of courage and determination.",
    "You're a model of consistency and reliability.",
    "You're a constant source of kindness and joy.",
    "You're an absolute treasure of a person.",
    "You have a heart full of generosity and love.",
    "You're a true inspiration to others in every way.",
]
flirting_lines = [
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Do you have a name or can I call you mine?",
    "Do you believe in love at first sight, or should I walk by again?",
    "I must be a snowflake because I've fallen for you.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Did it hurt when you fell from heaven?",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Is your dad a baker? Because you're a cutie pie.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a name, or can I call you mine?",
    "Can I borrow a kiss? I promise I'll give it back.",
    "Is your body from McDonald's? Because I'm lovin' it.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "I must be a snowflake because I've fallen for you.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Are you French? Because Eiffel for you.",
    "Are you an interior decorator? Because when I saw you, the entire room became beautiful.",
    "Do you have a sunburn, or are you always this hot?",
    "I must be lost because heaven is a long way from here.",
    "Are you a camera? Every time I look at you, I smile.",
    "Are you a bank loan? Because you have my interest.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a name or can I call you mine?",
    "Is your dad a baker? Because you're a cutie pie.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Did it hurt when you fell from heaven?",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Is your dad a baker? Because you're a cutie pie.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a name, or can I call you mine?",
    "Can I borrow a kiss? I promise I'll give it back.",
    "Is your body from McDonald's? Because I'm lovin' it.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "I must be a snowflake because I've fallen for you.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Are you French? Because Eiffel for you.",
    "Are you an interior decorator? Because when I saw you, the entire room became beautiful.",
    "Do you have a sunburn, or are you always this hot?",
    "I must be lost because heaven is a long way from here.",
    "Are you a camera? Every time I look at you, I smile.",
    "Are you a bank loan? Because you have my interest.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a name or can I call you mine?",
    "Is your dad a baker? Because you're a cutie pie.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Did it hurt when you fell from heaven?",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Is your dad a baker? Because you're a cutie pie.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a name, or can I call you mine?",
    "Can I borrow a kiss? I promise I'll give it back.",
    "Is your body from McDonald's? Because I'm lovin' it.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "I must be a snowflake because I've fallen for you.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Are you French? Because Eiffel for you.",
    "Are you an interior decorator? Because when I saw you, the entire room became beautiful.",
    "Do you have a sunburn, or are you always this hot?",
    "I must be lost because heaven is a long way from here.",
    "Are you a camera? Every time I look at you, I smile.",
    "Are you a bank loan? Because you have my interest.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a name or can I call you mine?",
    "Is your dad a baker? Because you're a cutie pie.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Did it hurt when you fell from heaven?",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Is your dad a baker? Because you're a cutie pie.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a name, or can I call you mine?",
    "Can I borrow a kiss? I promise I'll give it back.",
    "Is your body from McDonald's? Because I'm lovin' it.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "I must be a snowflake because I've fallen for you.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Are you French? Because Eiffel for you.",
    "Are you an interior decorator? Because when I saw you, the entire room became beautiful.",
    "Do you have a sunburn, or are you always this hot?",
    "I must be lost because heaven is a long way from here.",
    "Are you a camera? Every time I look at you, I smile.",
    "Are you a bank loan? Because you have my interest.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a name or can I call you mine?",
    "Is your dad a baker? Because you're a cutie pie.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Did it hurt when you fell from heaven?",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Is your dad a baker? Because you're a cutie pie.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a name, or can I call you mine?",
    "Can I borrow a kiss? I promise I'll give it back.",
    "Is your body from McDonald's? Because I'm lovin' it.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "I must be a snowflake because I've fallen for you.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Are you French? Because Eiffel for you.",
    "Are you an interior decorator? Because when I saw you, the entire room became beautiful.",
    "Do you have a sunburn, or are you always this hot?",
    "I must be lost because heaven is a long way from here.",
    "Are you a camera? Every time I look at you, I smile.",
    "Are you a bank loan? Because you have my interest.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a name or can I call you mine?",
    "Is your dad a baker? Because you're a cutie pie.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Do you have a map? I keep getting lost in your eyes.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "You must be a parking ticket because you've got 'Fine' written all over you."
]

full_name = input("Enter your full name: ")
gender_input = input("Enter your gender (male or female): ")

try:
    gender = Gender(gender_input.lower())
except ValueError:
    print("Invalid gender input. Please enter 'male' or 'female'.")
else:
    if gender == Gender.MALE:
        print(f"Hey {full_name}!, {random.choice(compliments)}")
    elif gender == Gender.FEMALE:
        print(f"Hey {full_name}!, {random.choice(flirting_lines)}")
